name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SUBSTITUTIONS: "
            _PROJECT=${{ secrets.GCP_PROJECT_ID }},\
            _REGION=us-central1,\
            # _PIPELINE_NAME=sentiment-analysis-tfx,\
            _REPO_URL=https://github.com/arturlunardi/sentiment-analysis-tfx,\
            _BRANCH=master,\
            "    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: check if something changed
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          base: 'master'        
          filters: |
            pipeline:
              - 'deployment/**'
      - name: trigger creating endpoint based on pipeline changes
        if: ${{ steps.filter.outputs.pipeline == 'true' }}
        run: |
          gcloud ai endpoints create \
          --region=LOCATION_ID \
          --display-name=ENDPOINT_NAME
