name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   SUBSTITUTIONS: "
#             _PROJECT=${{ secrets.GCP_PROJECT_ID }},\
#             _REGION=europe-west1,\
#             # _PIPELINE_NAME=sentiment-analysis-tfx,\
#             #_REPO_URL=https://github.com/arturlunardi/sentiment-analysis-tfx,\
#             _BRANCH=master,\
#             "    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: check if something changed
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          base: 'main'        
          filters: |
            pipeline:
              - 'deployment/**'
      - name: trigger creating endpoint based on pipeline changes
        if: ${{ steps.filter.outputs.pipeline == 'true' }}
        run: |
          gcloud ai endpoints deploy-model 1874702509730168832 \
          --region=europe-west1 \
          --model=6011364320586235904 \
          --display-name=model-by-github \
          --min-replica-count=1 \
          --max-replica-count=1 \
          --traffic-split=0=100
